-- ============================================================================
-- Math Tutor MVP — seed the skill ladder (75 CCSS skills, grades 3-5)
-- Apply AFTER 0001_init.sql. Idempotent (on conflict do nothing).
-- sequence_position is the array index 0..N (single monotonic ladder).
-- Equivalent to running supabase/seed/seed_skills.py; use whichever is convenient.
-- ============================================================================

insert into public.skills (curriculum_id, code, name, domain, grade, sequence_position)
select c.id, v.code, v.name, v.domain, v.grade, v.seq
from public.curricula c
cross join (values
  ('CCSS.3.OA.A.1', 'Interpret products of whole numbers (equal groups)', 'Operations & Algebraic Thinking', 3, 0),
  ('CCSS.3.OA.A.2', 'Interpret whole-number quotients (sharing & grouping)', 'Operations & Algebraic Thinking', 3, 1),
  ('CCSS.3.OA.A.3', 'Multiplication & division word problems within 100', 'Operations & Algebraic Thinking', 3, 2),
  ('CCSS.3.OA.A.4', 'Find the unknown in a multiplication or division equation', 'Operations & Algebraic Thinking', 3, 3),
  ('CCSS.3.OA.B.5', 'Apply properties of operations (commutative, associative, distributive)', 'Operations & Algebraic Thinking', 3, 4),
  ('CCSS.3.OA.B.6', 'Understand division as an unknown-factor problem', 'Operations & Algebraic Thinking', 3, 5),
  ('CCSS.3.OA.C.7', 'Fluently multiply and divide within 100', 'Operations & Algebraic Thinking', 3, 6),
  ('CCSS.3.OA.D.8', 'Solve two-step word problems using the four operations', 'Operations & Algebraic Thinking', 3, 7),
  ('CCSS.3.OA.D.9', 'Identify arithmetic patterns', 'Operations & Algebraic Thinking', 3, 8),
  ('CCSS.3.NBT.A.1', 'Round whole numbers to the nearest 10 or 100', 'Number & Operations in Base Ten', 3, 9),
  ('CCSS.3.NBT.A.2', 'Add and subtract within 1000', 'Number & Operations in Base Ten', 3, 10),
  ('CCSS.3.NBT.A.3', 'Multiply one-digit numbers by multiples of 10', 'Number & Operations in Base Ten', 3, 11),
  ('CCSS.3.NF.A.1', 'Understand a fraction as parts of a whole (1/b)', 'Number & Operations—Fractions', 3, 12),
  ('CCSS.3.NF.A.2', 'Understand fractions on a number line', 'Number & Operations—Fractions', 3, 13),
  ('CCSS.3.NF.A.3', 'Equivalent fractions and comparing fractions', 'Number & Operations—Fractions', 3, 14),
  ('CCSS.3.MD.A.1', 'Tell time to the minute and solve elapsed-time problems', 'Measurement & Data', 3, 15),
  ('CCSS.3.MD.A.2', 'Measure and estimate liquid volume and mass', 'Measurement & Data', 3, 16),
  ('CCSS.3.MD.B.3', 'Draw and interpret scaled picture and bar graphs', 'Measurement & Data', 3, 17),
  ('CCSS.3.MD.B.4', 'Measure lengths and show data on line plots', 'Measurement & Data', 3, 18),
  ('CCSS.3.MD.C.5', 'Understand area as unit squares', 'Measurement & Data', 3, 19),
  ('CCSS.3.MD.C.7', 'Relate area to multiplication and the distributive property', 'Measurement & Data', 3, 20),
  ('CCSS.3.MD.D.8', 'Solve perimeter problems for polygons', 'Measurement & Data', 3, 21),
  ('CCSS.3.G.A.1', 'Reason about shapes and their categories (quadrilaterals)', 'Geometry', 3, 22),
  ('CCSS.3.G.A.2', 'Partition shapes into parts with equal areas', 'Geometry', 3, 23),
  ('CCSS.4.OA.A.1', 'Interpret multiplication as a comparison', 'Operations & Algebraic Thinking', 4, 24),
  ('CCSS.4.OA.A.2', 'Multiplicative comparison word problems', 'Operations & Algebraic Thinking', 4, 25),
  ('CCSS.4.OA.A.3', 'Multistep word problems and interpreting remainders', 'Operations & Algebraic Thinking', 4, 26),
  ('CCSS.4.OA.B.4', 'Factors, multiples, prime and composite numbers', 'Operations & Algebraic Thinking', 4, 27),
  ('CCSS.4.OA.C.5', 'Generate and analyze number/shape patterns', 'Operations & Algebraic Thinking', 4, 28),
  ('CCSS.4.NBT.A.1', 'Place value: each place is 10x the place to its right', 'Number & Operations in Base Ten', 4, 29),
  ('CCSS.4.NBT.A.2', 'Read, write, and compare multi-digit numbers', 'Number & Operations in Base Ten', 4, 30),
  ('CCSS.4.NBT.A.3', 'Round multi-digit whole numbers', 'Number & Operations in Base Ten', 4, 31),
  ('CCSS.4.NBT.B.4', 'Add and subtract multi-digit numbers (standard algorithm)', 'Number & Operations in Base Ten', 4, 32),
  ('CCSS.4.NBT.B.5', 'Multiply up to 4-digit by 1-digit and 2-digit by 2-digit', 'Number & Operations in Base Ten', 4, 33),
  ('CCSS.4.NBT.B.6', 'Divide up to 4-digit dividends by 1-digit divisors', 'Number & Operations in Base Ten', 4, 34),
  ('CCSS.4.NF.A.1', 'Recognize and generate equivalent fractions', 'Number & Operations—Fractions', 4, 35),
  ('CCSS.4.NF.A.2', 'Compare fractions with different numerators and denominators', 'Number & Operations—Fractions', 4, 36),
  ('CCSS.4.NF.B.3', 'Add and subtract fractions with like denominators', 'Number & Operations—Fractions', 4, 37),
  ('CCSS.4.NF.B.4', 'Multiply a fraction by a whole number', 'Number & Operations—Fractions', 4, 38),
  ('CCSS.4.NF.C.5', 'Add fractions with denominators 10 and 100', 'Number & Operations—Fractions', 4, 39),
  ('CCSS.4.NF.C.6', 'Use decimal notation for fractions', 'Number & Operations—Fractions', 4, 40),
  ('CCSS.4.NF.C.7', 'Compare decimals to hundredths', 'Number & Operations—Fractions', 4, 41),
  ('CCSS.4.MD.A.1', 'Know relative sizes of measurement units and convert', 'Measurement & Data', 4, 42),
  ('CCSS.4.MD.A.2', 'Solve word problems involving measurement and conversion', 'Measurement & Data', 4, 43),
  ('CCSS.4.MD.A.3', 'Apply area and perimeter formulas for rectangles', 'Measurement & Data', 4, 44),
  ('CCSS.4.MD.C.5', 'Understand concepts of angles and angle measurement', 'Measurement & Data', 4, 45),
  ('CCSS.4.MD.C.6', 'Measure and sketch angles with a protractor', 'Measurement & Data', 4, 46),
  ('CCSS.4.MD.C.7', 'Solve problems with additive angle measures', 'Measurement & Data', 4, 47),
  ('CCSS.4.G.A.1', 'Draw and identify points, lines, rays, and angles', 'Geometry', 4, 48),
  ('CCSS.4.G.A.2', 'Classify two-dimensional figures by lines and angles', 'Geometry', 4, 49),
  ('CCSS.4.G.A.3', 'Recognize lines of symmetry', 'Geometry', 4, 50),
  ('CCSS.5.OA.A.1', 'Use parentheses and brackets; evaluate expressions', 'Operations & Algebraic Thinking', 5, 51),
  ('CCSS.5.OA.A.2', 'Write and interpret numerical expressions', 'Operations & Algebraic Thinking', 5, 52),
  ('CCSS.5.OA.B.3', 'Analyze patterns and relationships (ordered pairs)', 'Operations & Algebraic Thinking', 5, 53),
  ('CCSS.5.NBT.A.1', 'Place value: 10x and 1/10 relationships', 'Number & Operations in Base Ten', 5, 54),
  ('CCSS.5.NBT.A.2', 'Explain patterns with powers of 10', 'Number & Operations in Base Ten', 5, 55),
  ('CCSS.5.NBT.A.3', 'Read, write, and compare decimals to thousandths', 'Number & Operations in Base Ten', 5, 56),
  ('CCSS.5.NBT.A.4', 'Round decimals to any place', 'Number & Operations in Base Ten', 5, 57),
  ('CCSS.5.NBT.B.5', 'Multiply multi-digit whole numbers (standard algorithm)', 'Number & Operations in Base Ten', 5, 58),
  ('CCSS.5.NBT.B.6', 'Divide with up to 4-digit dividends and 2-digit divisors', 'Number & Operations in Base Ten', 5, 59),
  ('CCSS.5.NBT.B.7', 'Add, subtract, multiply, and divide decimals to hundredths', 'Number & Operations in Base Ten', 5, 60),
  ('CCSS.5.NF.A.1', 'Add and subtract fractions with unlike denominators', 'Number & Operations—Fractions', 5, 61),
  ('CCSS.5.NF.A.2', 'Word problems adding and subtracting fractions', 'Number & Operations—Fractions', 5, 62),
  ('CCSS.5.NF.B.3', 'Interpret a fraction as division of numerator by denominator', 'Number & Operations—Fractions', 5, 63),
  ('CCSS.5.NF.B.4', 'Multiply a fraction by a fraction or whole number', 'Number & Operations—Fractions', 5, 64),
  ('CCSS.5.NF.B.5', 'Interpret multiplication as scaling (resizing)', 'Number & Operations—Fractions', 5, 65),
  ('CCSS.5.NF.B.7', 'Divide unit fractions and whole numbers', 'Number & Operations—Fractions', 5, 66),
  ('CCSS.5.MD.A.1', 'Convert among different-sized measurement units', 'Measurement & Data', 5, 67),
  ('CCSS.5.MD.B.2', 'Make line plots with fractional measurements', 'Measurement & Data', 5, 68),
  ('CCSS.5.MD.C.3', 'Understand volume as unit cubes', 'Measurement & Data', 5, 69),
  ('CCSS.5.MD.C.5', 'Relate volume to multiplication (V = l x w x h)', 'Measurement & Data', 5, 70),
  ('CCSS.5.G.A.1', 'Understand the coordinate plane', 'Geometry', 5, 71),
  ('CCSS.5.G.A.2', 'Graph points on the coordinate plane to solve problems', 'Geometry', 5, 72),
  ('CCSS.5.G.B.3', 'Understand attributes belonging to categories of 2D figures', 'Geometry', 5, 73),
  ('CCSS.5.G.B.4', 'Classify two-dimensional figures in a hierarchy', 'Geometry', 5, 74)
) as v(code, name, domain, grade, seq)
where c.code = 'common_core'
on conflict (curriculum_id, code) do nothing;
